name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  

  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: devflexpro/archivarix-cms

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Tag Docker image with Git tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            TAG=${GITHUB_REF#refs/tags/}
            docker push $IMAGE_NAME:$TAG
          fi
